#!/usr/bin/bash
# description: Controls Ethercis Server
# processname: ecis-server
#
# SCRIPT created 15-10-2015, CCH
#-----------------------------------------------------------------------------------
UNAME=`uname`
HOSTNAME=`hostname`
export ECIS_DEPLOY_BASE=/opt/ecis
export SYSLIB=${ECIS_DEPLOY_BASE}/lib/system
export COMMONLIB=${ECIS_DEPLOY_BASE}/lib/common
export APPLIB=${ECIS_DEPLOY_BASE}/lib/application

# Mailer configuration
ECIS_MAILER=echo

# use the right jvm library depending on the OS
# NB: EtherCIS requires java 8
if [ :${UNAME}: = :Linux: ];
then
  JAVA_HOME=/opt/jdk1.8.0_60/jre
fi
if [ :${UNAME}: = :SunOS: ];
then
  JAVA_HOME=/jdk1.8.0_60/jre
fi

#force to use IPv4 so Jetty can bind to it instead of IPv6...
export _JAVA_OPTIONS="-Djava.net.preferIPv4Stack=true"

# runtime parameters
export JVM=${JAVA_HOME}/bin/java
export RUNTIME_HOME=/opt/ecis
export RUNTIME_ETC=/etc/opt/ecis
export RUNTIME_LOG=/var/opt/ecis
export RUNTIME_DIALECT=EHRSCAPE  #specifies the query dialect used in HTTP requests (REST)
export SERVER_PORT=8080 # the port address to bind to
export SERVER_HOST=188.166.246.78 # the network address to bind to

export MAILER_CONF=${RUNTIME_ETC}/xcmail.cf

export JOOQ_DIALECT=POSTGRES
JOOQ_DB_PORT=5432
JOOQ_DB_HOST=localhost
JOOQ_DB_SCHEMA=ethercis
export JOOQ_URL=jdbc:postgresql://${JOOQ_DB_HOST}:${JOOQ_DB_PORT}/${JOOQ_DB_SCHEMA}
export JOOQ_DB_LOGIN=postgres
export JOOQ_DB_PASSWORD=postgres

CLASSPATH=./:\
${JAVA_HOME}/lib:\
${APPLIB}/ecis-core.jar:\
${APPLIB}/ecis-knowledge-cache.jar:\
${APPLIB}/ecis-ehrdao.jar:\
${APPLIB}/ecis-servicemanager.jar:\
${APPLIB}/ecis-authenticateservice.jar:\
${APPLIB}/ecis-cacheknowledgeservice.jar:\
${APPLIB}/ecis-logonservice.jar:\
${APPLIB}/ecis-resourceaccessservice.jar:\
${APPLIB}/ecis-compositionservice.jar:\
${APPLIB}/ecis-partyidentifiedservice.jar:\
${APPLIB}/ecis-systemservice.jar:\
${APPLIB}/ecis-ehrservice.jar:\
${APPLIB}/ecis-vehrservice.jar:\
${APPLIB}/ehrxml.jar:\
${APPLIB}/oet-parser.jar:\
${APPLIB}/ecis-openehr.jar:\
${APPLIB}/types.jar:\
${APPLIB}/adl-parser-1.0.9.jar:\
${SYSLIB}/fst-2.40-onejar.jar:\
${SYSLIB}/jersey-json-1.19.jar:\
${SYSLIB}/gson-2.4.jar:\
${SYSLIB}/commons-collections4-4.0.jar:\
${SYSLIB}/jooq-3.5.3.jar:\
${SYSLIB}/postgresql-9.4-1204.jdbc42.jar:\
${SYSLIB}/dom4j-1.6.1.jar:\
${SYSLIB}/jetty-servlet-9.2.10.v20150310.jar:\
${SYSLIB}/thinkehr-framework-jsonlib-2.3.0-JL32.jar:\
${SYSLIB}/gson-jodatime-serialisers-1.2.0.jar


# launch server
# ecis server is run as user ethercis
su - ethercis << _ECIS
case "$1" in
  start)
    echo "ethercis startup"
     ( ${ECIS_MAILER} ${MAILER_CONF} "EtherCIS Startup" "Manual invocation of server startup" > /dev/null )&
    echo ${CLASSPATH}
    (
	${JVM} \
	-Xmx256M \
	-Xms256M \
	-server \
	-XX:-EliminateLocks \
	-XX:-UseVMInterruptibleIO \
	-cp ${CLASSPATH} \
	-Xdebug \
	-Xrunjdwp:transport=dt_socket,address=8000,suspend=n,server=y \
	-Djava.util.logging.config.file=${RUNTIME_ETC}/logging.properties \
	-Dlog4j.configuration=file:${RUNTIME_ETC}/log4j.xml \
	-Djava.awt.headless=true \
	-Djdbc.drivers=org.postgresql.Driver \
    -Dserver.node.name=testsg.ethercis.org \
	-Dcom.sun.management.jmxremote \
	-Dcom.sun.management.jmxremote.port=8999 \
    -Dcom.sun.management.jmxremote.local.only=false \
	-Dcom.sun.management.jmxremote.ssl=false \
	-Dcom.sun.management.jmxremote.authenticate=false \
    -Dfile.encoding=UTF-8 \
    -Djava.rmi.server.hostname=${SERVER_HOST} \
	-Djooq.dialect=${JOOQ_DIALECT} \
	-Djooq.url=${JOOQ_URL} \
	-Djooq.login=${JOOQ_DB_LOGIN} \
	-Djooq.password=${JOOQ_DB_PASSWORD} \
	-Druntime.etc=${RUNTIME_ETC} \
	 com.ethercis.vehr.Launcher \
	-propertyFile ${RUNTIME_ETC}/services.properties \
    -server_host ${SERVER_HOST} \
    -server_port 8080 \
 2>> ${RUNTIME_LOG}/ethercis_test.log >> ${RUNTIME_LOG}/ethercis_test.log &    )&
    ;;
  stop)
    ( ${ECIS_MAILER} ${MAILER_CONF} "Ethercis Stop" "Manual invocation of server STOP" > /dev/null )&
    echo "ethercis shutdown"
    pkill java
    ;;
  restart)
    ( ${ECIS_MAILER} ${MAILER_CONF} "Ethercis Restart" "Manual invocation of server RESTART" )&
    echo "ethercis restarting"
    $0 stop
    $0 start
    ;;
  clean)
    (${ECIS_MAILER} ${MAILER_CONF} "Ethercis CLEAR" "Manual invocation of server Clear logs" > dev/null )&
    echo "ethercis clear"
    $0 stop
	rm -rf {RUNTIME_LOG}/ethercis_test.log
    ;;
  *)
    echo "Usage: ecis-server {start|stop|restart|clean}"
    exit 1
esac
_ECIS
exit 0
# end of file

