#!/usr/bin/bash
# ethercis 1.1.1
# description: migrate a db 1.0 to the new json struct + containments
#
# script created 17.06.2016, cch
# rev September 2016, cch
#-----------------------------------------------------------------------------------
uname=`uname`
hostname=`hostname`
export ecis_deploy_base=/opt/ecis
export syslib=${ecis_deploy_base}/lib/system
export commonlib=${ecis_deploy_base}/lib/common
export applib=${ecis_deploy_base}/lib/application
export lib=${ecis_deploy_base}/lib/deploy

# mailer configuration
ecis_mailer=echo

# use the right jvm library depending on the os
# nb: ethercis requires java 8
if [ :${uname}: = :linux: ];
then
  java_home=/opt/jdk1.8.0_60/jre
fi
if [ :${uname}: = :sunos: ];
then
  java_home=/jdk1.8.0_60/jre
fi

#force to use ipv4 so jetty can bind to it instead of ipv6...
export _java_options="-djava.net.preferipv4stack=true"

# runtime parameters
export jvm=${java_home}/bin/java
export runtime_home=/opt/ecis
export runtime_etc=/etc/opt/ecis
export runtime_log=/var/opt/ecis
export runtime_dialect=ehrscape  #specifies the query dialect used in http requests (rest)
export server_port=8080 # the port address to bind to
export server_host=178.62.71.220 # the network address to bind to

export mailer_conf=${runtime_etc}/xcmail.cf

export jooq_dialect=postgres
jooq_db_port=5432
jooq_db_host=localhost
jooq_db_schema=ethercis
export jooq_url=jdbc:postgresql://${jooq_db_host}:${jooq_db_port}/${jooq_db_schema}
export jooq_db_login=postgres
export jooq_db_password=postgres

classpath=./:\
${java_home}/lib:\
${lib}/ecis-core-1.1.1-snapshot.jar:\
${lib}/ecis-knowledge-cache-1.1.0-snapshot.jar:\
${lib}/ecis-ehrdao-1.1.0-snapshot.jar:\
${lib}/jooq-pg-1.1.0-snapshot.jar:\
${lib}/aql-processor-1.1.0-snapshot.jar:\
${lib}/ecis-validation-1.0-snapshot.jar:\
${lib}/ecis-transform-1.0-snapshot.jar:\
${APPLIB}/ehrxml.jar:\
${APPLIB}/oet-parser.jar:\
${APPLIB}/ecis-openehr.jar:\
${APPLIB}/types.jar:\
${APPLIB}/adl-parser-1.0.9.jar:\


# launch migration
${JVM} \
	-cp ${CLASSPATH} \
	com.ethercis.dao.access.util.MigrateEntry \
	-ckm_archetype /etc/opt/ecis/knowledge/archetypes \
	-ckm_template /etc/opt/ecis/knowledge/templates \
	-ckm_opt /etc/opt/ecis/knowledge/operational_templates \
    -port 5432 \
	-all

# end of file


